name: Python package

on:
  push:
    branches:
      - "bra1"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to HuggingFace Hub
      uses: osbm/huggingface-login@v0.0.2
      with:
          username: ${{ secrets.HF_USERNAME }}
          password: ${{ secrets.HF_PASSWORD }}
    - name: Set up Python
      uses: actions/setup-python@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: execute py script # run file
      run: |
        python quantization.py
